name: Karma Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      id: node
    - name: Test
      run: |
        npm install
        node_modules/karma/bin/karma start karma.conf.js --log-level debug --single-run
